/// 
Class Auwais.FHIRRouter.RoutingRule Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "Auwais.FHIRRouter.RuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="" context="Auwais.FHIRRouter.RoutingEngine" production="HCCDEMOPKG.FoundationProduction">
<ruleSet name="" effectiveBegin="" effectiveEnd="">
<rule name="">
</rule>
</ruleSet>
</ruleDefinition>
}

}
